# Generated by Django 2.2.4 on 2019-11-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Numero', models.CharField(max_length=12)),
                ('Email', models.CharField(max_length=50)),
            ],
        ),
    ]
