# Generated by Django 2.2.4 on 2019-11-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191121_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
