# Generated by Django 2.2.4 on 2019-11-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20191123_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
