# Generated by Django 2.2.4 on 2019-11-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20191123_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='imagem',
            field=models.FileField(upload_to='media/'),
        ),
    ]
