# Generated by Django 2.2.4 on 2019-11-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20191123_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
