# Generated by Django 2.2.4 on 2019-11-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20191123_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='Descricoa',
            field=models.TextField(),
        ),
    ]
